services:

  otel-collector:
    image: otel/opentelemetry-collector:0.86.0
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml


  jaeger:
    image: jaegertracing/all-in-one:1.58
    ports:
      - "4317:4317"
      - "16686:16686"